### ISSUE TITLE
No Names on player icons

### ISSUE THREAD

**Issue by Remanent** [webbukkit/DynmapForge#42]
This post is being moved from [webbukkit/dynmap](https://github.com/webbukkit/dynmap/issues/1757) as i realized i posted it in the wrong place lol (better late than never i suppose)

I am currently running Forge 1.8-11.14.1.1334-universal, and using Dynmap-HEAD-Forge-1.8.0.jar (which /dynmap version reports  Dynmap version: core=2.2-SNAPSHOT-2042, plugin=2.2-alpha-1-41 )

I started using this version as the 2.1 version i had before wasn't rendering night time maps correctly.  While the 2.2 build 2042 does render the night, and display it correctly, it doesn't display names next to any of the player icons that are on the server, and it doesn't populate the side bar with their names either.  I have no other mods running besides dynmap (and forge to load dynmap).

Here's a picture showing no labels next to the player name, or in the player list (but you see a small box next to the players icon on the map where the name or healthbars would be (i have small heads enabled, and healthbars disabled in my configuration.txt

![nonames](https://cloud.githubusercontent.com/assets/1380222/6839600/64b05a72-d341-11e4-9b0b-3a6ef69f2960.png)

______________________________________________________________________________

After doing some further testing, using Dynmap 2.2 (version: core=2.2-SNAPSHOT-2044, plugin=2.2-alpha-2-46)

Builds including forge-1.8-11.14.1.1318-universal.jar appear to work, showing names on the player list, and on the character heads around the map, and after version forge-1.8-11.14.1.1319-universal.jar, they don't... i haven't tested every single build, but build 1318 has working names, and the 4+ versions i've tried after 1318 (1319, 1334, 1350, 1354 off the top of my head), the names don't appear on the map, or player list..

[In the changelog for build 1319, these are the listed changes:](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.8-11.14.1.1319/forge-1.8-11.14.1.1319-changelog.txt)

###### Build 1319:
this?->	*__matthewprenger: Add the ability to add prefixes and suffixes to the player's display name.__*
not this?->	LexManos: Add safty to URL detection in chat. Closes (#)1712

###### In Closing
I have been trying to find the specific changes within the Mineforge github, but am not sure how to find  them... (github link: https://github.com/MinecraftForge )

I'm sorry i can't provide more specific changes, or a fix... i don't know how to program in Java (I should probably learn one of these days lol, bucket list type stuff)  Hopefully this will point you in the correct direction..  I did test a few versions of the 11.14.0 builds, and they all had working names, that being said, 1299 had a nasty bug kicking ppl on ladders, swimming, etc. (for flying).

**Comment by elgribbo** [comment]
I just installed 2.1-SNAPSHOT-2032 on a Forge 1.8-11.14.1.1334 server and I have the same issue. No names are displayed on the map or in the player list.

**Comment by sasselin** [comment]
I have the forge forge-1.8-11.14.3.1450 & dynmap 2.1. Have the same bug

**Comment by sasselin** [comment]
I try with dynmap-2.2-alpha-2-52... same thing!

**Comment by Remanent** [comment]
it's the build of forge that's the problem. they changed something in the build 1319 of forge that broke the names showing up on the map in dynmap.  if you use forge-1.8-11.14.3.1318, with any current build of dynmap, the names will show, but if you use a more recent build of forge, the names cease to show.

**Comment by mikeprimm** [comment]
Try latest dev build for 2.2-alpha-3 - should fix this

**Comment by Remanent** [comment]
Will give it a go tomorrow.

**Comment by sasselin** [comment]
Nice!! Work for me! Thank you

**Comment by elgribbo** [comment]
Worked for me as well. Thanks!!

On Sat, Jul 11, 2015 at 1:35 PM, Sébastien Asselin <notifications@github.com

**Comment by Remanent** [comment]
Sorry I never got back on this, just tested it on 1450, works great.  Thanks for fixing this, sir.

Have a great day, and  thank you for the great mod.
