### ISSUE TITLE
1.8.9 support for SpongeForge

### ISSUE THREAD

**Issue by flash4203** [webbukkit/DynmapForge#53]
Hello I have noticed that the newer versions of Dynmap 

Dynmap-2.1-alpha-2-forge-1.8.0.jar  through to 
Dynmap-HEAD-forge-1.8.0.jar 
below is the crash in the server
[17:48:55] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraftforge.fml.common.WrongMinecraftVersionException: Wrong Minecraft version for Dynmap
Wrong Minecraft Versions!
Mod: Dynmap
Location: C:\Users\Richard Meen\Desktop\backup\mods\Dynmap-HEAD-forge-1.8.0.jar
Expected: [1.8,1.8]
Current: Minecraft 1.8.9

![dynmaphead](https://cloud.githubusercontent.com/assets/16855072/12531717/befc1a82-c1f9-11e5-8da9-9db8f5da6abc.png)

do not work with 1.8.9 where as the older 

Dynmap-2.1-forge-1.8.0
does work but does not show the username

![dynmapolder](https://cloud.githubusercontent.com/assets/16855072/12531727/0bdb9210-c1fa-11e5-9abe-99286d6f3759.png)

Thank you. 
Flash4203

**Comment by mikeprimm** [comment]
First test builds are available for 1.8.9 - http://dynmap.us/builds/DynmapForge/Dynmap-2.3-alpha-1-forge-1.8.9.jar - give em a look.

**Comment by flash4203** [comment]
Hello Mike and thank you. I Will try that later. I noticed When I do a full render with the current one it deletes all the already rendered world. I assumed it would just fix in the gaps so it's more Mapish if that makes sense. I had to /Dynmap radiusrender world to get sections done. Is this a bug or does it meant to happen? 
Thank you 
Flash4203

**Comment by mikeprimm** [comment]
That is because, as the error report says, it doesn't support loading chunks - so, when the world is fullrendered, it only renders the chunks already loaded - and then cleans up the rest of the map as being chunks that no longer exist.  That error means "this isn't going to work right on this version of MC".

**Comment by flash4203** [comment]
Hello

one thing I notice is the following

[18:00:31] [Server thread/WARN] [FML]: MOD HAS DIRECT REFERENCE 
System.exit() THIS IS NOT ALLOWED REROUTING TO FML!
[18:00:31] [Server thread/WARN] [FML]: Offendor: 
org/dynmap/jetty/server/ShutdownMonitor$ShutdownMonitorThread.run()V
[18:00:31] [Server thread/WARN] [FML]: Use FMLCommonHandler.exitJava instead
[18:00:31] [Server thread/WARN] [FML]: 
=============================================================

is this a bug?

sorry for sounding stupid
Flash4203

**Comment by rfcMike** [comment]
That's harmless BS from Forge - they try to get cute and detect calls to System.exit() for some reason, and the web server library we use (Jetty) happens to include the call in its bytes (even though we would never call the corresponding code).

**Comment by mikeprimm** [comment]
That's harmless BS from Forge - they try to get cute and detect calls to System.exit() for some reason, and the web server library we use (Jetty) happens to include the call in its bytes (even though we would never call the corresponding code).

**Comment by flash4203** [comment]
Sorry for not getting back sooner. It works perfectly and full rendered as well. 

Even the ore is all hidden :-p 

Thank you.

**Comment by skaor** [comment]
I use the last stable version of forge and spongeforge with the dynmap alpha 1 1.8.9 but when i try to reach the map on m'y browser i have a 500 error. 
I didnt check but their Is a log for dynmap ? Because in the server console i have no error

**Comment by euro1726** [comment]
hello i have http://dynmap.us/builds/DynmapForge/Dynmap-2.3-alpha-1-forge-1.8.9.jar on my server but on browser i have Error 500 can help me someone ?
