### ISSUE TITLE
Biomes O' Plenty renders black

### ISSUE THREAD

**Issue by LiskoSlayer63** [webbukkit/DynmapForge#63]
Dynmap renders Biomes O' Plenty blocks black, I suppose that this associated to the BoP config file. Dynmap tries to load "config/biomesoplenty/ids.cfg" but that file doesn't exist, but there's file called "config/biomesoplenty/biome_ids.json". I tried to extract the "BiomesOPlenty-texture.txt" and the "BiomesOPlenty-models.txt" from the "Dynmap.jar" to "dynmap/renderdata" and change the config file path but it didn't work.

There's a screenshot from the map:
![dynmap_bop](https://cloud.githubusercontent.com/assets/10125529/23012408/b9d688b8-f42e-11e6-957f-262e7acdbf21.png)

**Comment by gdude2002** [comment]
+1, also getting this problem.

![](https://dl.dropboxusercontent.com/u/1547120/ShareX/2017/February/vivaldi_2017-02-17_13-22-01.jpg)

**Comment by legracen** [comment]
+ Also getting this problem:
http://chaosportalshow.com/minemap/

**Comment by bhi-elliot** [comment]
Seems to still be happening.
Dynmap 2.4 Forge
Biomes O' Plenty 6.2.0.2267.

Thanks for the great mod! Appreciate it!
