### ISSUE TITLE
index.html shows <noscript> tag when Javascript is enabled 

### ISSUE THREAD

**Issue by Orcinuss** [webbukkit/DynmapForge#67]
I am using dynmap on 1.10.2. Dynamp seems to be starting correctly from the console and the web/tiles/ directory is full of rendered images. But the page shows up as just black. When I inspect the page, it just shows the <noscript> tag as if javascript is not enabled even though I am sure that it is. I don't know if my config is wrong or if there is a bug. Let me know.

Webserver:
http://thermacraft.us:20203

configuration.txt
https://pastebin.com/izfLbRWC

worlds.txt:
https://pastebin.com/rR3w5pdz

Relevant Console Info:
https://pastebin.com/6CU3hZrj

**Comment by mikeprimm** [comment]
I'm pretty sure the issue is the fact that you comment out line 38 of your configuration.txt:

class: org.dynmap.ClientConfigurationComponent

This is very required component for the UI to work right.
