### ISSUE TITLE
BoP + Other mods *WORKING* [MC 1.10.2] [Dynmap 3]

### ISSUE THREAD

**Issue by ChubbyPitbull** [webbukkit/DynmapForge#74]
I'd been having an issue with the models and texture files generated by DynmapBlockScan not being loaded for many major mods, causing those tiles to appear black and missing on my map. I did some initial research and noticed that the "modname:" in the models/textures files generated by DynmapBlockScan were always lowercase, but in the server logs the mods that didn't load were often capitalized. I posted some of what I found here: https://github.com/webbukkit/DynmapBlockScan/issues/4

I then pulled down the DynmapCore, DynmapCoreAPI, and DynmapForge projects and dug into the code. It appeared that Dynmap looks for the "modname:" in the loaded mod list, and if it doesn't find it, simply doesn't load those files. Additionally, it appeared that Dynmap needs the modname to be lower case to load the blocks, so when I simply edited the modname: field in the models/textures files to have the correct capitalization, Dynmap would activate those mods but then would not load any models or textures.

I edited the getModVersion function in src/main/java/org/dynmap/forge/DynmapPlugin.java to do a case in-sensitive search of the loaded mod list, using the models and textures files directly from DynmapBlockScan:

```java
@Override
public String getModVersion(String name) {
     //ModContainer mod = Loader.instance().getIndexedModList().get(name);
     ModContainer mod = null;
    Set<String> keySet= Loader.instance().getIndexedModList().keySet();
    for(String caseSensitiveModName : keySet)
    {
        if(caseSensitiveModName.equalsIgnoreCase(name))
        {
            Log.verboseinfo("getModVersion: Matched "+name+" to "+caseSensitiveModName+".");
            mod = Loader.instance().getIndexedModList().get(caseSensitiveModName);
            break;
        }
    }
    if (mod == null) return null;
    return mod.getVersion();
}
```

Now BiomesOPlenty, Quark, most of Botania, and a variety of other mods are all now working fine in Dynmap.

Excerpt of Dynmap Logs from server start using working Dynmap:
[fml-server-latest-excerpt.log](https://github.com/webbukkit/DynmapForge/files/1646694/fml-server-latest-excerpt.log)

In progress render of Dynmap map after adding in BoP models/textures files from DynmapBlockScan (base is in Moor):  ![dynmapbefore-after](https://user-images.githubusercontent.com/7650990/35154011-9b3e01e8-fcf6-11e7-9c41-db5b4b7e9161.PNG)

Close up of base after running fullrender and adding in all models/textures files from DynmapBlockScan (Botania flowers are visible as well): 
![dynmap-fullrender](https://user-images.githubusercontent.com/7650990/35154093-dae49ece-fcf6-11e7-8a92-625a1f840af8.PNG)

**Comment by artman41** [comment]
any chance you could upload a hotfixed jar with your fix included? @ChubbyPitbull

**Comment by ChubbyPitbull** [comment]
@artman41 not without @mikeprimm 's permission, it's his mod.

**Comment by generrosity** [comment]
Oooh! That sounds like some excellent work, and must have taken a while to diagnose through the code. Well done! I'm looking forward to seeing it land in HEAD.

**Comment by mikeprimm** [comment]
Nice - let me give this a closer look: I'll be happy to include the change.   Thanks, @ChubbyPitbull !!

**Comment by mikeprimm** [comment]
Just did a spin of v3.0 builds with a variant of the proposed fix.  Give them a look, and let me know if the fix continues to work as expected, @ChubbyPitbull and others!

**Comment by ChubbyPitbull** [comment]
Thanks @mikeprimm ! I'll pull down the latest and try it out!

**Comment by ChubbyPitbull** [comment]
@mikeprimm , I downloaded the http://mikeprimm.com/dynmap/builds/DynmapForge/Dynmap-3.0-alpha-1-forge-1.10.2.jar build from today, ran a fullrender, and everything's working great! Thank you!

[fml-server-latest.log](https://github.com/webbukkit/DynmapForge/files/1714490/fml-server-latest.log)

**Comment by mikeprimm** [comment]
@ChubbyPitbull Thank YOU for a solid root cause analysis :)

**Comment by MajorDeew** [comment]
I cannot find Dynmap forge v3 in your repos..
Does it still exist?

I found v3 in CourseForge, but it doesn't work very well..

Now I'm using Dynmap-3.0.1-forge-1.10.2.jar and DynmapBlockScan-3.0-SNAPSHOT-forge-1.10.2.jar
